name: Tests

on:
  pull_request:
    branches: [main]

jobs:
  build_nodejs_module:
    name: Build NodeJS module on Linux (Ubuntu)
    runs-on: ubuntu-latest
    steps:
      - name: Install System dependencies
        run: sudo apt install -y libatspi2.0-dev libnode-dev
      - name: Install node-gyp
        run: sudo npm install -g node-gyp
      - name: Install SWIG 4.1.0
        run: |
          wget "https://github.com/swig/swig/archive/refs/tags/v4.1.0.tar.gz"
          tar -axf v4.1.0.tar.gz
          cd swig-4.1.0
          ./autogen.sh
          ./configure
          make -j
          sudo make install
      - uses: actions/checkout@v3
      - name: Configure Project
        run: |
          mkdir build
          cd build
          cmake .. -DAXA_NODEJS_MODULE=ON
      - name: Build project
        run: |
          cd build
          make -j
